So there I was...
On my way to a big hot date...
When I realized I forgot the address.
To make matters worse, my cellphone was dead.
Luckily, I remembered she wrote her number on a napkin.
All I had to do was pop into a payphone and ring her up.
Nothing was going to ruin today.
Nothing...